### ISSUE TITLE
Streaming does not work?

### ISSUE THREAD

**Issue by mcdonoughdr** [vit9696/Shiki#8] opened 2017-07-22 22:32 UTC
Using this plugin with a GT 1030, and I can play downloaded movies but can't stream them in iTunes....

**Comment by vit9696** [comment] 2017-07-22 22:53
Duplicate of https://github.com/vit9696/Shiki/issues/5
TL;DR Pascal support is total rubbish in macos.

**Closed by vit9696** 2017-07-22 22:53 UTC
